# Generated by Django 4.2.3 on 2023-08-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangoRead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangacard',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
