# Generated by Django 4.2.3 on 2023-08-03 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MangoRead', '0002_mangacard_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangacard',
            name='description',
        ),
        migrations.AddField(
            model_name='mangacard',
            name='synopsis',
            field=models.TextField(blank=True, null=True, verbose_name='Синопсис'),
        ),
        migrations.AlterField(
            model_name='mangacard',
            name='genre',
            field=models.ManyToManyField(blank=True, to='MangoRead.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='mangacard',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mangacard',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='mangacard',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manga_type', to='MangoRead.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='mangacard',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Год'),
        ),
    ]
